# Generated by Django 3.2 on 2021-05-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.TextField(blank=True, max_length=10, null=True, verbose_name='Autor')),
                ('contenido', models.TextField(max_length=370, verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, upload_to='', verbose_name='Imagen')),
                ('update', models.DateField(auto_now_add=True, verbose_name='Fecha alta')),
            ],
        ),
    ]
