# Generated by Django 3.2 on 2021-05-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0002_alter_dato_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='allow',
            field=models.BooleanField(default=False, verbose_name='Autorizado'),
        ),
    ]
