# Generated by Django 3.2 on 2021-05-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0003_dato_allow'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
