# Generated by Django 3.2 on 2021-05-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0004_dato_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dato',
            name='likes',
        ),
    ]
