# Generated by Django 3.2 on 2021-05-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0006_alter_dato_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='Datosimg', verbose_name='Imágen'),
        ),
    ]
