# Generated by Django 3.2 on 2021-05-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0008_auto_20210520_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='autor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='dato',
            name='contenido',
            field=models.TextField(max_length=370, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='dato',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='Datosimg', verbose_name='Imágen'),
        ),
    ]
