# Generated by Django 3.2 on 2021-05-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0009_auto_20210520_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta'),
        ),
    ]
