# Generated by Django 3.2 on 2021-05-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0010_alter_dato_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='update',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha alta'),
        ),
    ]
